TEMPLATE=app
CONFIG+=qtopia
TARGET=photogallery

CONFIG+=quicklaunch singleexec

MODULES*=homeui

include(photogallery.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES
