TEMPLATE=app
CONFIG+=qtopia
TARGET=calculator

CONFIG+=quicklaunch singleexec

include(calculator.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

