qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=target
dir=src/$$TARGET
depends(3rdparty/libraries/sqlite)
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qtopiacore/corelib)
