qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=host
dir=src/$$TARGET
win32:depends(libraries/qt/winmain)
unix:depends(3rdparty/libraries/pthread)
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qt/tools/moc)
depends(libraries/qt/tools/uic)
depends(libraries/qt/tools/rcc)
