TEMPLATE	= lib
CONFIG		+= qtopia warn_on release
HEADERS		= notepadimpl.h
SOURCES		= notepadimpl.cpp
TARGET		= notepad
DESTDIR		= $(QPEDIR)/plugins/imagecodecs
INCLUDEPATH	+= $(QPEDIR)/include
DEPENDPATH      += $(QPEDIR)/include
LIBS            += -lqpe
VERSION		= 1.0.0
