#!/bin/sh
if [ -d /opt/teambuilder ]; then
    export PATH=/opt/teambuilder/bin:/usr/local/gcc-4.1.1/bin:$PATH
    export TEAMBUILDER_CC_VERSION=4.1.2
else
    export PATH=/usr/local/gcc-4.1.1/bin:$PATH
fi
