<!DOCTYPE TS><TS>
<context>
    <name>Advanced</name>
    <message>
        <source>Scientific</source>
        <translation>関数電卓</translation>
    </message>
</context>
<context>
    <name>FormAdvanced</name>
    <message>
        <source>M+</source>
        <translation>M+</translation>
    </message>
    <message>
        <source>MR</source>
        <translation>MR</translation>
    </message>
    <message>
        <source>MC</source>
        <translation>MC</translation>
    </message>
    <message>
        <source>CE/C</source>
        <translation>CE/C</translation>
    </message>
    <message>
        <source>asin</source>
        <translation>asin</translation>
    </message>
    <message>
        <source>acos</source>
        <translation>acos</translation>
    </message>
    <message>
        <source>atan</source>
        <translation>atan</translation>
    </message>
    <message>
        <source>&lt;-</source>
        <translation>&lt;-</translation>
    </message>
    <message>
        <source>sin</source>
        <translation>sin</translation>
    </message>
    <message>
        <source>cos</source>
        <translation>cos</translation>
    </message>
    <message>
        <source>tan</source>
        <translation>tan</translation>
    </message>
    <message>
        <source>n!</source>
        <translation>n!</translation>
    </message>
    <message>
        <source>ln</source>
        <translation>ln</translation>
    </message>
    <message>
        <source>+/-</source>
        <translation>+/-</translation>
    </message>
    <message>
        <source>log</source>
        <translation>log</translation>
    </message>
</context>
</TS>
