TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=parashoot

CONFIG+=quicklaunch

include(parashoot.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

