TEMPLATE=app
CONFIG+=qtopia
TARGET=camera

QTOPIA*=video
CONFIG+=quicklaunch singleexec

include(camera.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

