<!DOCTYPE TS><TS>
<context>
    <name>TimeZone</name>
    <message>
        <source>Rio Branco</source>
        <translation>リオブランコ</translation>
    </message>
    <message>
        <source>Yellowknife</source>
        <translation>イエローナイフ</translation>
    </message>
    <message>
        <source>Kuwait</source>
        <translation>クウェート</translation>
    </message>
    <message>
        <source>Merida</source>
        <translation>メリダ</translation>
    </message>
    <message>
        <source>Danmarkshavn</source>
        <translation>デンマークシャブン</translation>
    </message>
    <message>
        <source>Lome</source>
        <translation>ロメ</translation>
    </message>
    <message>
        <source>Bujumbura</source>
        <translation>ブジュンブラ</translation>
    </message>
    <message>
        <source>Tripoli</source>
        <translation>トリポリ</translation>
    </message>
    <message>
        <source>Sakhalin</source>
        <translation>サハリン</translation>
    </message>
    <message>
        <source>Brunei</source>
        <translation>ブルネイ</translation>
    </message>
    <message>
        <source>Nairobi</source>
        <translation>ナイロビ</translation>
    </message>
    <message>
        <source>Kuching</source>
        <translation>クチン</translation>
    </message>
    <message>
        <source>Detroit</source>
        <translation>デトロイト</translation>
    </message>
    <message>
        <source>Jayapura</source>
        <translation>ジャヤプラ</translation>
    </message>
    <message>
        <source>Melbourne</source>
        <translation>メルボルン</translation>
    </message>
    <message>
        <source>Beirut</source>
        <translation>ベイルート</translation>
    </message>
    <message>
        <source>Sao Paulo</source>
        <translation>サンパウロ</translation>
    </message>
    <message>
        <source>Aqtobe</source>
        <translation>アクトベ</translation>
    </message>
    <message>
        <source>South Georgia</source>
        <translation>サウスジョージア</translation>
    </message>
    <message>
        <source>Chihuahua</source>
        <translation>チワワ</translation>
    </message>
    <message>
        <source>Los Angeles</source>
        <translation>ロサンゼルス</translation>
    </message>
    <message>
        <source>Maseru</source>
        <translation>マセル</translation>
    </message>
    <message>
        <source>Swift Current</source>
        <translation>スイフトカレント</translation>
    </message>
    <message>
        <source>Irkutsk</source>
        <translation>イルクスク</translation>
    </message>
    <message>
        <source>Dhaka</source>
        <translation>ダッカ</translation>
    </message>
    <message>
        <source>Bamako</source>
        <translation>バマコ</translation>
    </message>
    <message>
        <source>Cordoba</source>
        <translation>コルドバ</translation>
    </message>
    <message>
        <source>Managua</source>
        <translation>マナグア</translation>
    </message>
    <message>
        <source>Noronha</source>
        <translation>ノロハ</translation>
    </message>
    <message>
        <source>Chisinau</source>
        <translation>クシャトリア</translation>
    </message>
    <message>
        <source>Comoro</source>
        <translation>コモロ</translation>
    </message>
    <message>
        <source>Mawson</source>
        <translation>モーソン</translation>
    </message>
    <message>
        <source>DumontDUrville</source>
        <translation>ドマンドリビレ</translation>
    </message>
    <message>
        <source>Montreal</source>
        <translation>モントリオール</translation>
    </message>
    <message>
        <source>Accra</source>
        <translation>アクラ</translation>
    </message>
    <message>
        <source>Sofia</source>
        <translation>ソフィア</translation>
    </message>
    <message>
        <source>Saigon</source>
        <translation>サイゴン</translation>
    </message>
    <message>
        <source>Vaduz</source>
        <translation>ブァドゥーズ</translation>
    </message>
    <message>
        <source>Nauru</source>
        <translation>ナウル</translation>
    </message>
    <message>
        <source>Norfolk</source>
        <translation>ノーフォーク</translation>
    </message>
    <message>
        <source>Taipei</source>
        <translation>タイペイ</translation>
    </message>
    <message>
        <source>Colombo</source>
        <translation>コロンボ</translation>
    </message>
    <message>
        <source>Montevideo</source>
        <translation>モンテビデオ</translation>
    </message>
    <message>
        <source>Harare</source>
        <translation>ハーラル</translation>
    </message>
    <message>
        <source>Port of Spain</source>
        <translation>ポルトオブスペイン</translation>
    </message>
    <message>
        <source>Ljubljana</source>
        <translation>リュブリヤナ</translation>
    </message>
    <message>
        <source>Maputo</source>
        <translation>マプト</translation>
    </message>
    <message>
        <source>Kwajalein</source>
        <translation>クアジャリン</translation>
    </message>
    <message>
        <source>Sydney</source>
        <translation>シドニー</translation>
    </message>
    <message>
        <source>Uzhgorod</source>
        <translation>ウズゴルド</translation>
    </message>
    <message>
        <source>Skopje</source>
        <translation>スコプリエ</translation>
    </message>
    <message>
        <source>Adelaide</source>
        <translation>アデレード</translation>
    </message>
    <message>
        <source>Yakutsk</source>
        <translation>ヤクーツク</translation>
    </message>
    <message>
        <source>Gaborone</source>
        <translation>ガボローネ</translation>
    </message>
    <message>
        <source>Pacific</source>
        <translation>太平洋</translation>
    </message>
    <message>
        <source>St Lucia</source>
        <translation>セントルキア</translation>
    </message>
    <message>
        <source>Pontianak</source>
        <translation>ポンティアナック</translation>
    </message>
    <message>
        <source>La Paz</source>
        <translation>ラバス</translation>
    </message>
    <message>
        <source>Kerguelen</source>
        <translation>クルゲレン</translation>
    </message>
    <message>
        <source>Glace Bay</source>
        <translation>グレースベイ</translation>
    </message>
    <message>
        <source>El Aaiun</source>
        <translation>エルアイウン</translation>
    </message>
    <message>
        <source>Niue</source>
        <translation>ニウエ</translation>
    </message>
    <message>
        <source>Recife</source>
        <translation>レシーフ</translation>
    </message>
    <message>
        <source>Thule</source>
        <translation>チューレ</translation>
    </message>
    <message>
        <source>St Vincent</source>
        <translation>セントビンセント</translation>
    </message>
    <message>
        <source>Aden</source>
        <translation>アデン</translation>
    </message>
    <message>
        <source>Ujung Pandang</source>
        <translation>ウジュンバンダン</translation>
    </message>
    <message>
        <source>Vostok</source>
        <translation>ヴォストーク</translation>
    </message>
    <message>
        <source>Rangoon</source>
        <translation>ラグーン</translation>
    </message>
    <message>
        <source>Bangkok</source>
        <translation>バンコック</translation>
    </message>
    <message>
        <source>Shiprock</source>
        <translation>シップロック</translation>
    </message>
    <message>
        <source>Anguilla</source>
        <translation>アングィラ</translation>
    </message>
    <message>
        <source>Istanbul</source>
        <translation>イスタンブール</translation>
    </message>
    <message>
        <source>Ashgabat</source>
        <translation>アシカバッド</translation>
    </message>
    <message>
        <source>Sarajevo</source>
        <translation>サラエボ</translation>
    </message>
    <message>
        <source>Vancouver</source>
        <translation>バンクーバ</translation>
    </message>
    <message>
        <source>Paris</source>
        <translation>パリ</translation>
    </message>
    <message>
        <source>Godthab</source>
        <translation>ゴッドホーブ</translation>
    </message>
    <message>
        <source>Australia</source>
        <translation>オーストラリア</translation>
    </message>
    <message>
        <source>Africa</source>
        <translation>アフリカ</translation>
    </message>
    <message>
        <source>Omsk</source>
        <translation>オムスク</translation>
    </message>
    <message>
        <source>Casablanca</source>
        <translation>カサブランカ</translation>
    </message>
    <message>
        <source>Madrid</source>
        <translation>マドリッド</translation>
    </message>
    <message>
        <source>Goose Bay</source>
        <translation>グースベイ</translation>
    </message>
    <message>
        <source>Tashkent</source>
        <translation>タシュケント</translation>
    </message>
    <message>
        <source>Truk</source>
        <translation>トラック</translation>
    </message>
    <message>
        <source>Paramaribo</source>
        <translation>パラマリボ</translation>
    </message>
    <message>
        <source>Marquesas</source>
        <translation>マークイス</translation>
    </message>
    <message>
        <source>Regina</source>
        <translation>レジャイナ</translation>
    </message>
    <message>
        <source>Gambier</source>
        <translation>ガンビール</translation>
    </message>
    <message>
        <source>Cayenne</source>
        <translation>カイニンヌ</translation>
    </message>
    <message>
        <source>Thunder Bay</source>
        <translation>サンダーベイ</translation>
    </message>
    <message>
        <source>Center</source>
        <translation>センター</translation>
    </message>
    <message>
        <source>Grenada</source>
        <translation>グレナダ</translation>
    </message>
    <message>
        <source>Minsk</source>
        <translation>ミンスク</translation>
    </message>
    <message>
        <source>Muscat</source>
        <translation>マスカット</translation>
    </message>
    <message>
        <source>Costa Rica</source>
        <translation>コスタリカ</translation>
    </message>
    <message>
        <source>Pangnirtung</source>
        <translation>パングニタン</translation>
    </message>
    <message>
        <source>Rarotonga</source>
        <translation>ラロトンガ</translation>
    </message>
    <message>
        <source>Tallinn</source>
        <translation>タリン</translation>
    </message>
    <message>
        <source>Kiritimati</source>
        <translation>キリティマティ</translation>
    </message>
    <message>
        <source>Athens</source>
        <translation>アテネ</translation>
    </message>
    <message>
        <source>Jakarta</source>
        <translation>ジャカルタ</translation>
    </message>
    <message>
        <source>Monaco</source>
        <translation>モナコ</translation>
    </message>
    <message>
        <source>Bahrain</source>
        <translation>バーレーン</translation>
    </message>
    <message>
        <source>Longyearbyen</source>
        <translation>ロングヤーブエン</translation>
    </message>
    <message>
        <source>Aruba</source>
        <translation>アルーバ</translation>
    </message>
    <message>
        <source>Curacao</source>
        <translation>キュラソー</translation>
    </message>
    <message>
        <source>Gaza</source>
        <translation>ガザ</translation>
    </message>
    <message>
        <source>Novosibirsk</source>
        <translation>ノボシビリスク</translation>
    </message>
    <message>
        <source>Bangui</source>
        <translation>バンギ</translation>
    </message>
    <message>
        <source>Cayman</source>
        <translation>ケイマン</translation>
    </message>
    <message>
        <source>Amsterdam</source>
        <translation>アムステルダム</translation>
    </message>
    <message>
        <source>Dar es Salaam</source>
        <translation>ダルニスザラーム</translation>
    </message>
    <message>
        <source>Bissau</source>
        <translation>ビサウ</translation>
    </message>
    <message>
        <source>Guyana</source>
        <translation>ガイアナ</translation>
    </message>
    <message>
        <source>Caracas</source>
        <translation>カラカス</translation>
    </message>
    <message>
        <source>Blantyre</source>
        <translation>ブランタイア</translation>
    </message>
    <message>
        <source>Anadyr</source>
        <translation>アナドリ</translation>
    </message>
    <message>
        <source>Catamarca</source>
        <translation>カタマルカ</translation>
    </message>
    <message>
        <source>Santiago</source>
        <translation>サンティアゴ</translation>
    </message>
    <message>
        <source>New York</source>
        <translation>ニューヨーク</translation>
    </message>
    <message>
        <source>Chagos</source>
        <translation>シャゴス</translation>
    </message>
    <message>
        <source>Porto Velho</source>
        <translation>ポルトベロー</translation>
    </message>
    <message>
        <source>Jujuy</source>
        <translation>ジュジュ</translation>
    </message>
    <message>
        <source>Noumea</source>
        <translation>ヌメア</translation>
    </message>
    <message>
        <source>Asia</source>
        <translation>アジア</translation>
    </message>
    <message>
        <source>Phnom Penh</source>
        <translation>プノンペン</translation>
    </message>
    <message>
        <source>Rome</source>
        <translation>ローマ</translation>
    </message>
    <message>
        <source>Maceio</source>
        <translation>マセイオ</translation>
    </message>
    <message>
        <source>Tirane</source>
        <translation>ティラネ</translation>
    </message>
    <message>
        <source>Dawson Creek</source>
        <translation>ドーソンクリーク</translation>
    </message>
    <message>
        <source>Ndjamena</source>
        <translation>ヌジャメナ</translation>
    </message>
    <message>
        <source>Thimphu</source>
        <translation>ティンブー</translation>
    </message>
    <message>
        <source>Faeroe</source>
        <translation>フェロー</translation>
    </message>
    <message>
        <source>Karachi</source>
        <translation>カラチ</translation>
    </message>
    <message>
        <source>Monticello</source>
        <translation>モンテビデオ</translation>
    </message>
    <message>
        <source>St Helena</source>
        <translation>セントヘレナ</translation>
    </message>
    <message>
        <source>Guatemala</source>
        <translation>グアテマラ</translation>
    </message>
    <message>
        <source>Araguaina</source>
        <translation>アラグアイア</translation>
    </message>
    <message>
        <source>Louisville</source>
        <translation>ルーイヴェル</translation>
    </message>
    <message>
        <source>Buenos Aires</source>
        <translation>ブエノスアイレス</translation>
    </message>
    <message>
        <source>Davis</source>
        <translation>デービス</translation>
    </message>
    <message>
        <source>Abidjan</source>
        <translation>アビジャン</translation>
    </message>
    <message>
        <source>Prague</source>
        <translation>プラハ</translation>
    </message>
    <message>
        <source>Moscow</source>
        <translation>モスクワ</translation>
    </message>
    <message>
        <source>Chatham</source>
        <translation>シャタン</translation>
    </message>
    <message>
        <source>Mogadishu</source>
        <translation>モガディシオ</translation>
    </message>
    <message>
        <source>Galapagos</source>
        <translation>カラパゴス</translation>
    </message>
    <message>
        <source>Addis Ababa</source>
        <translation>アディスアベバ</translation>
    </message>
    <message>
        <source>Mahe</source>
        <translation>マヘー</translation>
    </message>
    <message>
        <source>Antigua</source>
        <translation>アンティグア</translation>
    </message>
    <message>
        <source>Jerusalem</source>
        <translation>エルサレム</translation>
    </message>
    <message>
        <source>Tahiti</source>
        <translation>タヒチ</translation>
    </message>
    <message>
        <source>Fiji</source>
        <translation>フィージー</translation>
    </message>
    <message>
        <source>Funafuti</source>
        <translation>フナフティ</translation>
    </message>
    <message>
        <source>Johannesburg</source>
        <translation>ヨハネスブルク</translation>
    </message>
    <message>
        <source>Monterrey</source>
        <translation>モンテレイ</translation>
    </message>
    <message>
        <source>Havana</source>
        <translation>ハバナ</translation>
    </message>
    <message>
        <source>Bratislava</source>
        <translation>ブラティスラヴァ</translation>
    </message>
    <message>
        <source>Baku</source>
        <translation>バク</translation>
    </message>
    <message>
        <source>Wake</source>
        <translation>ウェーク</translation>
    </message>
    <message>
        <source>Lisbon</source>
        <translation>リズボン</translation>
    </message>
    <message>
        <source>Belem</source>
        <translation>ベレン</translation>
    </message>
    <message>
        <source>Kosrae</source>
        <translation>コスラエ</translation>
    </message>
    <message>
        <source>Indian</source>
        <translation>インド洋</translation>
    </message>
    <message>
        <source>Tehran</source>
        <translation>テヘラン</translation>
    </message>
    <message>
        <source>Tortola</source>
        <translation>トルトラ</translation>
    </message>
    <message>
        <source>Helsinki</source>
        <translation>ヘルシンキ</translation>
    </message>
    <message>
        <source>Zagreb</source>
        <translation>ザグレブ</translation>
    </message>
    <message>
        <source>Krasnoyarsk</source>
        <translation>クラノスヤルスク</translation>
    </message>
    <message>
        <source>Perth</source>
        <translation>パース</translation>
    </message>
    <message>
        <source>Andorra</source>
        <translation>アンドラ</translation>
    </message>
    <message>
        <source>Pago Pago</source>
        <translation>パゴパゴ</translation>
    </message>
    <message>
        <source>Madeira</source>
        <translation>マデイラ</translation>
    </message>
    <message>
        <source>Tijuana</source>
        <translation>ティファナ</translation>
    </message>
    <message>
        <source>Puerto Rico</source>
        <translation>プエルトルコ</translation>
    </message>
    <message>
        <source>Dublin</source>
        <translation>ダブリン</translation>
    </message>
    <message>
        <source>Kigali</source>
        <translation>キガリ</translation>
    </message>
    <message>
        <source>Cancun</source>
        <translation>カンカン</translation>
    </message>
    <message>
        <source>Riyadh</source>
        <translation>リヤード</translation>
    </message>
    <message>
        <source>Yerevan</source>
        <translation>イエレバン</translation>
    </message>
    <message>
        <source>Atlantic</source>
        <translation>大西洋</translation>
    </message>
    <message>
        <source>Cambridge Bay</source>
        <translation>ケンブリッジベイ</translation>
    </message>
    <message>
        <source>Calcutta</source>
        <translation>カルカッタ</translation>
    </message>
    <message>
        <source>Fakaofo</source>
        <translation>ファカオフォ</translation>
    </message>
    <message>
        <source>Zurich</source>
        <translation>チューリッヒ</translation>
    </message>
    <message>
        <source>Phoenix</source>
        <translation>フェニックス</translation>
    </message>
    <message>
        <source>Monrovia</source>
        <translation>モンロヴィア</translation>
    </message>
    <message>
        <source>Auckland</source>
        <translation>オークランド</translation>
    </message>
    <message>
        <source>Manila</source>
        <translation>マニラ</translation>
    </message>
    <message>
        <source>Guam</source>
        <translation>グアム</translation>
    </message>
    <message>
        <source>Easter</source>
        <translation>イースター</translation>
    </message>
    <message>
        <source>Nouakchott</source>
        <translation>ヌクアショット</translation>
    </message>
    <message>
        <source>Johnston</source>
        <translation>ジョンストーン</translation>
    </message>
    <message>
        <source>St Thomas</source>
        <translation>セントトーマス</translation>
    </message>
    <message>
        <source>Palau</source>
        <translation>パラウ</translation>
    </message>
    <message>
        <source>Guadeloupe</source>
        <translation>グアドループ</translation>
    </message>
    <message>
        <source>Budapest</source>
        <translation>ブタペスト</translation>
    </message>
    <message>
        <source>Berlin</source>
        <translation>ベルリン</translation>
    </message>
    <message>
        <source>Montserrat</source>
        <translation>モントセラト</translation>
    </message>
    <message>
        <source>Scoresbysund</source>
        <translation>スコレスバイサンド</translation>
    </message>
    <message>
        <source>Rosario</source>
        <translation>ロサリオ</translation>
    </message>
    <message>
        <source>Lusaka</source>
        <translation>ルサカ</translation>
    </message>
    <message>
        <source>Malabo</source>
        <translation>マラボ</translation>
    </message>
    <message>
        <source>Antananarivo</source>
        <translation>アンタラナリヴォ</translation>
    </message>
    <message>
        <source>Kinshasa</source>
        <translation>キンシャサ</translation>
    </message>
    <message>
        <source>America</source>
        <translation>アメリカ</translation>
    </message>
    <message>
        <source>Mbabane</source>
        <translation>ムババメ</translation>
    </message>
    <message>
        <source>Efate</source>
        <translation>エファテェ</translation>
    </message>
    <message>
        <source>Dawson</source>
        <translation>ドーソン</translation>
    </message>
    <message>
        <source>Enderbury</source>
        <translation>エンダベリ</translation>
    </message>
    <message>
        <source>Europe</source>
        <translation>ヨーロッパ</translation>
    </message>
    <message>
        <source>Edmonton</source>
        <translation>エドモントン</translation>
    </message>
    <message>
        <source>Cuiaba</source>
        <translation>クヤバ</translation>
    </message>
    <message>
        <source>Denver</source>
        <translation>デンバー</translation>
    </message>
    <message>
        <source>Antarctica</source>
        <translation>南極大陸</translation>
    </message>
    <message>
        <source>Boise</source>
        <translation>ボイシ</translation>
    </message>
    <message>
        <source>Rainy River</source>
        <translation>レイニーリバー</translation>
    </message>
    <message>
        <source>Dushanbe</source>
        <translation>ダスバネ</translation>
    </message>
    <message>
        <source>Manaus</source>
        <translation>マナッサス</translation>
    </message>
    <message>
        <source>Port-au-Prince</source>
        <translation>ポルトプランス</translation>
    </message>
    <message>
        <source>Tongatapu</source>
        <translation>トンガ</translation>
    </message>
    <message>
        <source>Anchorage</source>
        <translation>アンカレッジ</translation>
    </message>
    <message>
        <source>Guadalcanal</source>
        <translation>グアンダルカナル</translation>
    </message>
    <message>
        <source>Grand Turk</source>
        <translation>グランドターク</translation>
    </message>
    <message>
        <source>Zaporozhye</source>
        <translation>ザポロージェ</translation>
    </message>
    <message>
        <source>Maldives</source>
        <translation>モルジブ</translation>
    </message>
    <message>
        <source>Nassau</source>
        <translation>ナッサウ</translation>
    </message>
    <message>
        <source>Dubai</source>
        <translation>デュバイ</translation>
    </message>
    <message>
        <source>Indianapolis</source>
        <translation>インディアナポリス</translation>
    </message>
    <message>
        <source>Djibouti</source>
        <translation>ジブティ</translation>
    </message>
    <message>
        <source>Marengo</source>
        <translation>マレンゴ</translation>
    </message>
    <message>
        <source>Arctic</source>
        <translation>北極大陸</translation>
    </message>
    <message>
        <source>Syowa</source>
        <translation>ショーワ</translation>
    </message>
    <message>
        <source>Shanghai</source>
        <translation>上海</translation>
    </message>
    <message>
        <source>Copenhagen</source>
        <translation>コペンハーゲン</translation>
    </message>
    <message>
        <source>America/North Dakota</source>
        <translation>アメリカ/北ダコタ</translation>
    </message>
    <message>
        <source>Tbilisi</source>
        <translation>トビリシ</translation>
    </message>
    <message>
        <source>Christmas</source>
        <translation>クリスマス</translation>
    </message>
    <message>
        <source>Dominica</source>
        <translation>ドミニカ</translation>
    </message>
    <message>
        <source>Tunis</source>
        <translation>チョニス</translation>
    </message>
    <message>
        <source>Knox</source>
        <translation>ノックス</translation>
    </message>
    <message>
        <source>Wallis</source>
        <translation>ヴァリス</translation>
    </message>
    <message>
        <source>Honolulu</source>
        <translation>ホノルル</translation>
    </message>
    <message>
        <source>Boa Vista</source>
        <translation>ボアヴィスタ</translation>
    </message>
    <message>
        <source>Gibraltar</source>
        <translation>ジブラルタル</translation>
    </message>
    <message>
        <source>Samara</source>
        <translation>サマラ</translation>
    </message>
    <message>
        <source>Jamaica</source>
        <translation>ジャマイカ</translation>
    </message>
    <message>
        <source>Azores</source>
        <translation>アゾレス</translation>
    </message>
    <message>
        <source>Aqtau</source>
        <translation>アクトー</translation>
    </message>
    <message>
        <source>Belgrade</source>
        <translation>ベォグラード</translation>
    </message>
    <message>
        <source>Mauritius</source>
        <translation>モーリシャス</translation>
    </message>
    <message>
        <source>Bishkek</source>
        <translation>ビシュコッ</translation>
    </message>
    <message>
        <source>Hermosillo</source>
        <translation>エルモニショ</translation>
    </message>
    <message>
        <source>Algiers</source>
        <translation>アルジェリア</translation>
    </message>
    <message>
        <source>Urumqi</source>
        <translation>ウルムチ</translation>
    </message>
    <message>
        <source>Belfast</source>
        <translation>ベルファースト</translation>
    </message>
    <message>
        <source>Santo Domingo</source>
        <translation>サントドミンゴ</translation>
    </message>
    <message>
        <source>London</source>
        <translation>ロンドン</translation>
    </message>
    <message>
        <source>Vladivostok</source>
        <translation>ウラジオストック</translation>
    </message>
    <message>
        <source>Qatar</source>
        <translation>カタール</translation>
    </message>
    <message>
        <source>Chongqing</source>
        <translation>重慶</translation>
    </message>
    <message>
        <source>Luanda</source>
        <translation>ルアンダ</translation>
    </message>
    <message>
        <source>Dakar</source>
        <translation>ダクラ</translation>
    </message>
    <message>
        <source>Katmandu</source>
        <translation>カトマンドゥー</translation>
    </message>
    <message>
        <source>Khartoum</source>
        <translation>ハルトゥーン</translation>
    </message>
    <message>
        <source>Pyongyang</source>
        <translation>ピョンヤン</translation>
    </message>
    <message>
        <source>Majuro</source>
        <translation>マジュロ</translation>
    </message>
    <message>
        <source>Timbuktu</source>
        <translation>ティンブクトゥ</translation>
    </message>
    <message>
        <source>McMurdo</source>
        <translation>マックマード</translation>
    </message>
    <message>
        <source>Jan Mayen</source>
        <translation>ヤンマイエン</translation>
    </message>
    <message>
        <source>Choibalsan</source>
        <translation>チョイバルサン</translation>
    </message>
    <message>
        <source>Kabul</source>
        <translation>カーブル</translation>
    </message>
    <message>
        <source>Barbados</source>
        <translation>バルバトス</translation>
    </message>
    <message>
        <source>Martinique</source>
        <translation>マルティーノ</translation>
    </message>
    <message>
        <source>Almaty</source>
        <translation>アルマリ</translation>
    </message>
    <message>
        <source>Conakry</source>
        <translation>コナクリ</translation>
    </message>
    <message>
        <source>Pitcairn</source>
        <translation>ピトケルン</translation>
    </message>
    <message>
        <source>South Pole</source>
        <translation>サウスポール</translation>
    </message>
    <message>
        <source>Apia</source>
        <translation>アピア</translation>
    </message>
    <message>
        <source>Vilnius</source>
        <translation>ビヒアス</translation>
    </message>
    <message>
        <source>Harbin</source>
        <translation>ハルビン</translation>
    </message>
    <message>
        <source>Stanley</source>
        <translation>スタンレー</translation>
    </message>
    <message>
        <source>Dili</source>
        <translation>ディリ</translation>
    </message>
    <message>
        <source>Samarkand</source>
        <translation>サマルカンド</translation>
    </message>
    <message>
        <source>Magadan</source>
        <translation>マガダン</translation>
    </message>
    <message>
        <source>Ceuta</source>
        <translation>セクタ</translation>
    </message>
    <message>
        <source>Belize</source>
        <translation>ベリーズ</translation>
    </message>
    <message>
        <source>Warsaw</source>
        <translation>ワルシャワ</translation>
    </message>
    <message>
        <source>Porto-Novo</source>
        <translation>ポルトノヴォ</translation>
    </message>
    <message>
        <source>Midway</source>
        <translation>ミッドウェイ</translation>
    </message>
    <message>
        <source>Riga</source>
        <translation>リガ</translation>
    </message>
    <message>
        <source>Asmera</source>
        <translation>アスマラ</translation>
    </message>
    <message>
        <source>Halifax</source>
        <translation>ハリファックス</translation>
    </message>
    <message>
        <source>Vienna</source>
        <translation>ウィーン</translation>
    </message>
    <message>
        <source>Broken Hill</source>
        <translation>ブロークンヒル</translation>
    </message>
    <message>
        <source>Amman</source>
        <translation>アマン</translation>
    </message>
    <message>
        <source>Kampala</source>
        <translation>カンパラ</translation>
    </message>
    <message>
        <source>Whitehorse</source>
        <translation>ホワイトホース</translation>
    </message>
    <message>
        <source>Guayaquil</source>
        <translation>グアヤキル</translation>
    </message>
    <message>
        <source>Brussels</source>
        <translation>ブリュッセル</translation>
    </message>
    <message>
        <source>Port Moresby</source>
        <translation>ポートモンスビー</translation>
    </message>
    <message>
        <source>Lindeman</source>
        <translation>リンデマン</translation>
    </message>
    <message>
        <source>Reykjavik</source>
        <translation>レイキャビーク</translation>
    </message>
    <message>
        <source>Vevay</source>
        <translation>ベベイ</translation>
    </message>
    <message>
        <source>Tegucigalpa</source>
        <translation>テグシガルパ</translation>
    </message>
    <message>
        <source>Cairo</source>
        <translation>カイロ</translation>
    </message>
    <message>
        <source>Nome</source>
        <translation>ノーム</translation>
    </message>
    <message>
        <source>Tokyo</source>
        <translation>東京</translation>
    </message>
    <message>
        <source>Kamchatka</source>
        <translation>カムチャツカ</translation>
    </message>
    <message>
        <source>Menominee</source>
        <translation>メノミニー</translation>
    </message>
    <message>
        <source>Cocos</source>
        <translation>ココス</translation>
    </message>
    <message>
        <source>Brazzaville</source>
        <translation>ブラザビル</translation>
    </message>
    <message>
        <source>Vatican</source>
        <translation>バチカン</translation>
    </message>
    <message>
        <source>Mexico City</source>
        <translation>メキシコシティ</translation>
    </message>
    <message>
        <source>Freetown</source>
        <translation>フリータウン</translation>
    </message>
    <message>
        <source>Fortaleza</source>
        <translation>フォルタレザ</translation>
    </message>
    <message>
        <source>Baghdad</source>
        <translation>バグダット</translation>
    </message>
    <message>
        <source>Malta</source>
        <translation>マルタ</translation>
    </message>
    <message>
        <source>Ouagadougou</source>
        <translation>ワガドゥグ</translation>
    </message>
    <message>
        <source>El Salvador</source>
        <translation>エルサルバドレ</translation>
    </message>
    <message>
        <source>Seoul</source>
        <translation>ソウル</translation>
    </message>
    <message>
        <source>Rankin Inlet</source>
        <translation>ランキンインレット</translation>
    </message>
    <message>
        <source>Libreville</source>
        <translation>リーブルヴィル</translation>
    </message>
    <message>
        <source>Tarawa</source>
        <translation>タラワ</translation>
    </message>
    <message>
        <source>Stockholm</source>
        <translation>ストックフォルム</translation>
    </message>
    <message>
        <source>Panama</source>
        <translation>パナマ</translation>
    </message>
    <message>
        <source>Banjul</source>
        <translation>バンジュール</translation>
    </message>
    <message>
        <source>Lima</source>
        <translation>リマ</translation>
    </message>
    <message>
        <source>Macau</source>
        <translation>マカオ</translation>
    </message>
    <message>
        <source>San Marino</source>
        <translation>サンマリノ</translation>
    </message>
    <message>
        <source>Iqaluit</source>
        <translation>イキルト</translation>
    </message>
    <message>
        <source>Juneau</source>
        <translation>ジュノー</translation>
    </message>
    <message>
        <source>Mayotte</source>
        <translation>マヨット</translation>
    </message>
    <message>
        <source>Casey</source>
        <translation>ケーシー</translation>
    </message>
    <message>
        <source>Eirunepe</source>
        <translation>イールネペ</translation>
    </message>
    <message>
        <source>Canary</source>
        <translation>カナリー</translation>
    </message>
    <message>
        <source>Niamey</source>
        <translation>ニアメー</translation>
    </message>
    <message>
        <source>Nicosia</source>
        <translation>ニッコシア</translation>
    </message>
    <message>
        <source>Yap</source>
        <translation>ヤップ</translation>
    </message>
    <message>
        <source>Mendoza</source>
        <translation>メンドサ</translation>
    </message>
    <message>
        <source>Oslo</source>
        <translation>オスロ</translation>
    </message>
    <message>
        <source>Adak</source>
        <translation>アダック</translation>
    </message>
    <message>
        <source>Palmer</source>
        <translation>パルメラ</translation>
    </message>
    <message>
        <source>Saipan</source>
        <translation>サイパン</translation>
    </message>
    <message>
        <source>Vientiane</source>
        <translation>ベトナム</translation>
    </message>
    <message>
        <source>Winnipeg</source>
        <translation>ウィニペグ</translation>
    </message>
    <message>
        <source>St Johns</source>
        <translation>セントジョーンズ</translation>
    </message>
    <message>
        <source>Simferopol</source>
        <translation>シムフェロポリ</translation>
    </message>
    <message>
        <source>Hobart</source>
        <translation>ホーバート</translation>
    </message>
    <message>
        <source>Bucharest</source>
        <translation>ブカレスト</translation>
    </message>
    <message>
        <source>Lord Howe</source>
        <translation>ロードハウ</translation>
    </message>
    <message>
        <source>Miquelon</source>
        <translation>ミクロン</translation>
    </message>
    <message>
        <source>Lagos</source>
        <translation>ラゴス</translation>
    </message>
    <message>
        <source>Bogota</source>
        <translation>ボゴタ</translation>
    </message>
    <message>
        <source>Reunion</source>
        <translation>ルエニオン</translation>
    </message>
    <message>
        <source>Ponape</source>
        <translation>ポナペ</translation>
    </message>
    <message>
        <source>Hong Kong</source>
        <translation>香港</translation>
    </message>
    <message>
        <source>Qyzylorda</source>
        <translation>キジルオルダ</translation>
    </message>
    <message>
        <source>Inuvik</source>
        <translation>インビック</translation>
    </message>
    <message>
        <source>Nipigon</source>
        <translation>ニピゴン</translation>
    </message>
    <message>
        <source>Douala</source>
        <translation>ドゥアーラ</translation>
    </message>
    <message>
        <source>Damascus</source>
        <translation>ダマスカス</translation>
    </message>
    <message>
        <source>Lubumbashi</source>
        <translation>ルブンバシ</translation>
    </message>
    <message>
        <source>Yakutat</source>
        <translation>ヤクタット</translation>
    </message>
    <message>
        <source>Cape Verde</source>
        <translation>ケープベルデ</translation>
    </message>
    <message>
        <source>Sao Tome</source>
        <translation>サントーメ</translation>
    </message>
    <message>
        <source>Oral</source>
        <translation>オラール</translation>
    </message>
    <message>
        <source>Mazatlan</source>
        <translation>マサトラン</translation>
    </message>
    <message>
        <source>St Kitts</source>
        <translation>セントキット</translation>
    </message>
    <message>
        <source>Kaliningrad</source>
        <translation>カリーニングラード</translation>
    </message>
    <message>
        <source>America/Kentucky</source>
        <translation>アメリカ</translation>
    </message>
    <message>
        <source>Kashgar</source>
        <translation>カシュガル</translation>
    </message>
    <message>
        <source>Chicago</source>
        <translation>シカゴ</translation>
    </message>
    <message>
        <source>Kiev</source>
        <translation>キエフ</translation>
    </message>
    <message>
        <source>Yekaterinburg</source>
        <translation>イカテエリンブルグ</translation>
    </message>
    <message>
        <source>Singapore</source>
        <translation>シンガポール</translation>
    </message>
    <message>
        <source>America/Indiana</source>
        <translation>アメリカ/インディアナ</translation>
    </message>
    <message>
        <source>Luxembourg</source>
        <translation>ルクセンプルグ</translation>
    </message>
    <message>
        <source>Bermuda</source>
        <translation>ベルヌーダ</translation>
    </message>
    <message>
        <source>Windhoek</source>
        <translation>ヴィントフーク</translation>
    </message>
    <message>
        <source>Darwin</source>
        <translation>ダーウィン</translation>
    </message>
    <message>
        <source>Kuala Lumpur</source>
        <translation>クアランプール</translation>
    </message>
    <message>
        <source>Asuncion</source>
        <translation>アスンシオン</translation>
    </message>
</context>
</TS>
