qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=target
dir=src/$$TARGET
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qtopiacore/gui)
depends(libraries/qtopiacore/network)
depends(libraries/qtopiacore/corelib)
