#!/bin/sh

echo "RUNNING GREENPHONE QTOPIA SXE/LIDS RULES"

test -z $QTOPIA_DIR && { echo "\$QTOPIA_DIR not defined!"; exit 1; }

# =============================================================================
#
# Set up update directory and SXE database
#
# =============================================================================
test -z $UPDATE_DIR && { echo "\$UPDATE_DIR not defined!"; exit 1; }
/bin/mkdir -p $UPDATE_DIR/bin

test -z $SXE_DATABASE && { echo "\$SXE_DATABASE not defined!"; exit 1; }
/bin/mkdir -p $SXE_DATABASE
for i in manifest installs sxe.policy keyfile sxe.profiles keyfile.sequence; do
    /bin/cp -a $QTOPIA_DIR/etc/$i $SXE_DATABASE/$i
done
lidsconf -A -o $SXE_DATABASE -j DENY

# =============================================================================
#
# Protect Qtopia filesystem
#
# =============================================================================

# Protect $QTOPIA_DIR and $UPDATE_DIR
# Here we protect $QTOPIA_DIR and $UPDATE_DIR directly. Some processes require
# write access to $QTOPIA_DIR to create a database journal file. These
# processes should be members of the 'prefix' SXE domain.
lidsconf -A -o $QTOPIA_DIR -j READONLY
lidsconf -A -o $UPDATE_DIR -j READONLY
lidsconf -A -o $QTOPIA_DIR/bin -j DENY
lidsconf -A -o $QTOPIA_DIR/bin -j DENY

# the quicklauched apps need to be protected for policies to be applied to
# them, so that suid can be used
for i in $QTOPIA_DIR/plugins/application/*; do
    lidsconf -A -o $i -j READONLY
done
for i in $UPDATE_DIR/plugins/application/*; do
    if [ "$i" != "$UPDATE_DIR/plugins/application/*" ]; then
        lidsconf -A -o $i -j READONLY
    fi
done


# Grant privileges to qpe.sh
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $QTOPIA_DIR/bin/qpe -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $QTOPIA_DIR/bin/startupflags.sh -i 1 -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $QTOPIA_DIR/bin/chvol -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $QTOPIA_DIR/bin/apm -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $QTOPIA_DIR/bin/phonebounce -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o /usr/bin/logger -j READONLY
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o $UPDATE_DIR/etc -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o /tmp -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/qpe.sh -o CAP_KILL -j GRANT

# Grant privileges to bootchart for profiling of qpe
lidsconf -A -s /sbin/bootchartd -o $QTOPIA_DIR/bin/qpe -j READONLY

# Protect SXE scripts
lidsconf -A -o $QTOPIA_DIR/etc -j READONLY
lidsconf -A -o $QTOPIA_DIR/etc/sxe_domains -j DENY
lidsconf -A -o $QTOPIA_DIR/etc/sxe_qtopia -j DENY
lidsconf -A -o $QTOPIA_DIR/etc/sxe_qtopia/sxe_sandbox -j DENY
lidsconf -A -o $QTOPIA_DIR/etc/sxe_qtopia/sxe_reloadconf -j DENY 
lidsconf -A -s $QTOPIA_DIR/etc/sxe_qtopia/sxe_reloadconf -o /etc/lids/lids.secret -j READONLY
lidsconf -A -o $QTOPIA_DIR/etc/sxe_qtopia/sxe_unsandbox -j DENY

# Protect SXE configuration files
lidsconf -A -o $SXE_DATABASE/sxe.policy -j DENY
lidsconf -A -o $QTOPIA_DIR/etc/sxe.profiles -j READONLY
lidsconf -A -o $SXE_DATABASE/installs -j DENY
lidsconf -A -o $SXE_DATABASE/manifest -j DENY
lidsconf -A -o $SXE_DATABASE/keyfile -j DENY

# Grant privileges to rc.lids
lidsconf -A -o /etc/rc.d/rc.lids -j READONLY
lidsconf -A -s /etc/rc.d/rc.lids -o $QTOPIA_DIR/etc/sxe_qtopia/sxe_qtopia -j READONLY

# Grant privileges to syslogd
lidsconf -A -s /sbin/syslogd -o $QTOPIA_DIR/bin/docapi-rescan.sh -i 1 -j READONLY

# =============================================================================
#
# Grant privileges to the server
#
# =============================================================================
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o $QTOPIA_DIR/etc -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /etc/pointercal -j WRITE

lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /proc -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /proc/sys/lids/locks -j READONLY

# GreenphoneHardware server tasks uses these to mount miniSD cards
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /sbin/fsck -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /bin/mount -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/qpe -o /bin/umount -j READONLY

# GPRS support
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qtopia-pppd-internal -o $QTOPIA_DIR/bin/qtopia-pppd-internal -j READONLY
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /usr/sbin/pppd -j READONLY
lidsconf -A POSTBOOT -s /usr/sbin/pppd -o $QTOPIA_DIR/bin/qtopia-pppd-internal -i 1 -j READONLY

# Generic device nodes
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/tty0 -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/console -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/video -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/ptyp0 -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/ttyp0 -j WRITE

# Greenphone specific devices nodes
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/omega_chgled -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/omega_kpbl -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/omega_vibrator -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/omega_detect -j READONLY
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/lcdctrl -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/ipmc -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/qpe -o /dev/ts -j READONLY

# =============================================================================
#
# Grant privileges to Qtopia helper applications
#
# =============================================================================

# Grant privileges to sxe_policy_runner
lidsconf -A -s $QTOPIA_DIR/bin/sxe_policy_runner -o $SXE_DATABASE/manifest -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/sxe_policy_runner -o $SXE_DATABASE/installs -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sxe_policy_runner -o $SXE_DATABASE/sxe.policy -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sxe_policy_runner -o $QTOPIA_DIR/etc/sxe_domains -j READONLY

# Grant privileges to Synchronization
lidsconf -A -s $QTOPIA_DIR/bin/qdsync -o $QTOPIA_DIR/bin/usb-gadget.sh -j READONLY

# Grant privileges to qtopia-pppd-internal
lidsconf -A -s $QTOPIA_DIR/bin/qtopia-pppd-internal -o $QTOPIA_DIR/bin/qcop -j READONLY

# =============================================================================
#
# Grant privileges to system integration helper scripts
#
# =============================================================================

# Grant privileges to lan-network
lidsconf -A -s $QTOPIA_DIR/bin/lan-network -o $QTOPIA_DIR/bin/lan-network -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/lan-network -o /usr/bin/logger -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/lan-network -o /etc/resolvconf -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/lan-network -o /etc -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/lan-network -o /tmp -i 1 -j WRITE

# Grant privileges to ppp-network
lidsconf -A -s $QTOPIA_DIR/bin/ppp-network -o $QTOPIA_DIR/bin/ppp-network -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/ppp-network -o /etc/resolvconf -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/ppp-network -o /etc -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/ppp-network -o /tmp -i 1 -j WRITE
lidsconf -A -s $QTOPIA_DIR/bin/ppp-network -o /usr/sbin/pppd -j READONLY

# Grant privileges to usb-gadget.sh
for i in $QTOPIA_DIR/bin/usb-gadget-*.sh; do
    lidsconf -A -s $i -o $i -j READONLY
    lidsconf -A -s $i -o $QTOPIA_DIR/bin/usb-gadget.sh -j READONLY
done
lidsconf -A -s $QTOPIA_DIR/bin/usb-gadget.sh -o $QTOPIA_DIR/bin/usb-gadget.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/usb-gadget.sh -o $QTOPIA_DIR/bin/qcop -j READONLY

# Grant privileges to sdio-wifi.sh
lidsconf -A -s $QTOPIA_DIR/bin/sdio-wifi.sh -o $QTOPIA_DIR/bin/sdio-wifi.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-wifi.sh -o /sbin/rmmod -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-wifi.sh -o /sbin/insmod -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-wifi.sh -o $QTOPIA_DIR/bin/qcop -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-wifi.sh -o $QTOPIA_DIR/bin/sdcard-umount.sh -j READONLY

# Grant privileges to sdio-storage.sh
lidsconf -A -s $QTOPIA_DIR/bin/sdio-storage.sh -o $QTOPIA_DIR/bin/sdio-storage.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-storage.sh -o /sbin/rmmod -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdio-storage.sh -o /sbin/insmod -j READONLY

# Grant privileges to bluetooth-wakeup.sh
lidsconf -A -s $QTOPIA_DIR/bin/bluetooth-wakeup.sh -o $QTOPIA_DIR/bin/bluetooth-wakeup.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/bluetooth-wakeup.sh -o /usr/bin/killall -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/bluetooth-wakeup.sh -o /sbin/rmmod -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/bluetooth-wakeup.sh -o /sbin/insmod -j READONLY

# Grant privileges to at
lidsconf -A -s $QTOPIA_DIR/bin/at -o $QTOPIA_DIR/bin/at -j READONLY

# Grant privileges to targzip and targunzip
lidsconf -A -s $QTOPIA_DIR/bin/targzip -o $QTOPIA_DIR/bin/targzip -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/tarungzip -o $QTOPIA_DIR/bin/tarungzip -j READONLY

# Grant privileges to qtopia-addmimetype
lidsconf -A -s $QTOPIA_DIR/bin/qtopia-addmimetype -o $QTOPIA_DIR/bin/qtopia-addmimetype -j READONLY

# =============================================================================
#
# Grant privileges to devtools helper scripts
#
# =============================================================================

# Grant privileges to docpai-rescan.sh
lidsconf -A -s $QTOPIA_DIR/bin/docapi-rescan.sh -o $QTOPIA_DIR/bin/docapi-rescan.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/docapi-rescan.sh -o $QTOPIA_DIR/bin/qcop -j READONLY

# Grant privileges to sdcard-umount.sh
lidsconf -A -s $QTOPIA_DIR/bin/sdcard-umount.sh -o $QTOPIA_DIR/bin/sdcard-umount.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdcard-umount.sh -o /bin/umount -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/sdcard-umount.sh -o $QTOPIA_DIR/bin/qcop -j READONLY

# Grant privileges to network-services-start.sh and network-services-stop.sh
lidsconf -A -s $QTOPIA_DIR/bin/network-services-start.sh -o $QTOPIA_DIR/bin/qcop -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/network-services-start.sh -o $QTOPIA_DIR/bin/network-services-start.sh -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/network-services-stop.sh -o $QTOPIA_DIR/bin/qcop -j READONLY
lidsconf -A -s $QTOPIA_DIR/bin/network-services-stop.sh -o $QTOPIA_DIR/bin/network-services-stop.sh -j READONLY

# Grant privileges to startupflags.sh
lisdconf -A -S $QTOPIA_DIR/bin/startupflags.sh -o $QTOPIA_DIR/bin/startupflags.sh -j READONLY

# =============================================================================
#
# Grant privileges to applications that should really be moved to the rootfs
#
# =============================================================================

# chvol needs access to the mixer
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/chvol -o /dev/mixer -j WRITE

# apm needs access to ipmc, sdcard_pm and PSSR
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm.bin -o /dev/ipmc -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm.bin -o /dev/sdcard_pm -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm.bin -o /dev/omega_bcm2121 -j WRITE
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm -o $QTOPIA_DIR/bin/apm -j READONLY
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm -o $QTOPIA_DIR/bin/apm.bin -j READONLY
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm -o $QTOPIA_DIR/bin/usb-gadget.sh -j READONLY
lidsconf -A POSTBOOT -s $QTOPIA_DIR/bin/apm -o /proc/bulverde/registers/PSSR -j WRITE

