qtopia_project(qtopiacore)
qt=host
dir=tools/assistant/$$TARGET
# generated by extract_qt_dependencies
# do not modify below this line!
depends(tools/qt/assistant/lib/fulltextsearch)
depends(libraries/qt/sql)
depends(libraries/qt/xml)
depends(libraries/qt/gui)
depends(libraries/qt/corelib)
