TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=appservices

CONFIG+=quicklaunch

include(appservices.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

