qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=staticlib
qt=host
dir=src/tools/$$TARGET
# Don't die on Windows!
!equals(QT_MINOR_VERSION,5):QMAKE_EXTRA_TARGETS+=install
requires(equals(QT_MINOR_VERSION,5))
# generated by extract_qt_dependencies
# do not modify below this line!
