DBUS_PREFIX=$$(DBUS_PREFIX)

TEMPLATE=app
CONFIG-=qt
SOURCES=main.cpp
INCLUDEPATH+=$$DBUS_PREFIX/lib/dbus-1.0/include $$DBUS_PREFIX/include/dbus-1.0
LIBS+=$$DBUS_PREFIX/lib/libdbus-1.so
DEFINES+=DBUS_API_SUBJECT_TO_CHANGE
