TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=minesweep

CONFIG+=quicklaunch

include(minesweep.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

