qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=app
qt=target
dir=src/tools/$$TARGET
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qtopiacore/tools/bootstrap)
