#!/bin/sh

QTOPIA_TOOLS=/mnt/user/tools
gifanim $QTOPIA_TOOLS/splash-shutdown-exit.gif &

killall qpe.sh
killall qpe
killall sipagent
killall qss
killall quicklauncher
killall mediaplayer
killall sxemonitor

while [ $# -gt 0 ]; do
    case $1 in
        -r)
            exec reboot
            ;;
        -h)
            exec poweroff
            ;;
        *)
            ;;
    esac
    shift
done

exec poweroff

