#!/bin/sh
TOOLCHAIN=/scratchbox/compilers/cs2005q3.2-glibc2.5-arm
#TOOLCHAIN=/scratchbox/compilers/cs2005q3.2-glibc-arm

USE_TB=0
TB_CC_PREFIX=arm-linux-
TB_CC_VER=auto
TB_SYS=arm:nokia
export PKG_CONFIG_PREFIX=$TOOLCHAIN/arm-none-linux-gnueabi
export PKG_CONFIG_PATH=$PKG_CONFIG_PREFIX/lib/pkgconfig
export TOOLCHAIN
