qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=ignore_errors lib
qt=host
dir=tools/designer/src/$$TARGET
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qt/corelib)
