TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=device_updater

PLUGIN_FOR=qtopia
PLUGIN_TYPE=qdsync

QTOPIA=base
MODULES*=qdsync_common

include(plugin.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

