TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=dialing

PLUGIN_FOR=qtopia
PLUGIN_TYPE=network

QTOPIA*=comm
enable_cell:QTOPIA*=phone

include(dialing.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

