TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=beaming

QTOPIA*=comm
CONFIG+=quicklaunch

include(beaming.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

