TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=homestyle

PLUGIN_TYPE=styles
PLUGIN_FOR=qt

QTOPIA+=gfx
MODULES*=homeui

include(home.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

