qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=target
dir=src/$$TARGET
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qtopiacore/gui)
depends(libraries/qtopiacore/network)
depends(libraries/qtopiacore/corelib)
PHONON_MAJOR_VERSION = $${QT_MAJOR_VERSION}
PHONON_MINOR_VERSION = 1
PHONON_PATCH_VERSION = $${QT_PATCH_VERSION}
VERSION = $${PHONON_MAJOR_VERSION}.$${PHONON_MINOR_VERSION}.$${PHONON_PATCH_VERSION}
