TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=btsettings

QTOPIA*=comm
CONFIG+=quicklaunch

include(btsettings.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

