qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=app rpath ignore_errors
qt=host
dir=tools/linguist/$$TARGET
depends(tools/qt/assistant/lib)
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qt/network)
depends(tools/qt/designer/src/uitools)
depends(libraries/qt/xml)
depends(libraries/qt/gui)
depends(libraries/qt/corelib)
