TEMPLATE=app
CONFIG+=qtopia
TARGET=mappingdemo

QTOPIA*=whereabouts
CONFIG+=quicklaunch

include(mappingdemo.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES
