TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=lan

PLUGIN_FOR=qtopia
PLUGIN_TYPE=network

QTOPIA*=comm

include(lan.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

