#!/bin/sh

export TOOLCHAIN=/opt/toolchains/armv5te-eabi

if [ -d /opt/teambuilder ]; then
    export PATH="$DEVICE_CONFIG_PATH/bin:/opt/teambuilder/bin:$TOOLCHAIN/bin:$PATH"
    echo "$TEAMBUILDER_CC_VERSION" | grep ':' >/dev/null 2>&1
    if [ $? -eq 0 ]; then
        export TEAMBUILDER_CC_VERSION="arm-linux-*:4.1.1;$(echo $TEAMBUILDER_CC_VERSION | sed 's/arm-linux[^:]*:[[digit].][[digit].]*;*//')"
    else
        export TEAMBUILDER_CC_VERSION="arm-linux-*:4.1.1;*:$(echo $TEAMBUILDER_CC_VERSION | sed 's/arm-linux[^:]*:[[digit].][[digit].]*;*//')"
    fi
    if [ "$TEAMBUILDER_SYSTEM" = 'arm:eabi' ]; then
        unset TEAMBUILDER_SYSTEM
    fi
else
    # don't destroy the environment if $TOOLCHAIN/bin is already somewhere in the $PATH
    if ! echo "$PATH" | grep "$TOOLCHAIN/bin" ; then
        export PATH="$TOOLCHAIN/bin:$PATH"
    fi
fi

PKG_CONFIG_PATH=/opt/toolchains/armv5te-eabi/arm-angstrom-linux-gnueabi/lib/pkgconfig

