<!DOCTYPE TS><TS>
<context>
    <name>Engine</name>
    <message>
        <source>Error in main programs: LCD has not been set</source>
        <translation>主要プログラムにエラー：LCDが設定されていません</translation>
    </message>
    <message>
        <source>Not a number</source>
        <translation>数字ではありません</translation>
    </message>
    <message>
        <source>Infinity</source>
        <translation>無限大</translation>
    </message>
    <message>
        <source>Not a positive number</source>
        <translation>正数ではありません</translation>
    </message>
    <message>
        <source>Not an integer</source>
        <translation>整数ではありません</translation>
    </message>
    <message>
        <source>Out of range</source>
        <translation>限度を越えています</translation>
    </message>
    <message>
        <source>Divide by zero error</source>
        <translation>除数が0です、エラー</translation>
    </message>
    <message>
        <source>Not solvable</source>
        <translation>解決できません</translation>
    </message>
    <message>
        <source>Error</source>
        <translation>エラー</translation>
    </message>
</context>
<context>
    <name>Type1BaseInputWidget</name>
    <message>
        <source>7</source>
        <translation>7</translation>
    </message>
    <message>
        <source>4</source>
        <translation>4</translation>
    </message>
    <message>
        <source>1</source>
        <translation>1</translation>
    </message>
    <message>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <source>8</source>
        <translation>8</translation>
    </message>
    <message>
        <source>5</source>
        <translation>5</translation>
    </message>
    <message>
        <source>2</source>
        <translation>2</translation>
    </message>
    <message>
        <source>9</source>
        <translation>9</translation>
    </message>
    <message>
        <source>6</source>
        <translation>6</translation>
    </message>
    <message>
        <source>3</source>
        <translation>3</translation>
    </message>
    <message>
        <source>=</source>
        <translation>=</translation>
    </message>
    <message>
        <source>+</source>
        <translation>+</translation>
    </message>
    <message>
        <source>-</source>
        <translation>-</translation>
    </message>
    <message>
        <source>x</source>
        <translation>x</translation>
    </message>
    <message>
        <source>/</source>
        <translation>/</translation>
    </message>
</context>
<context>
    <name>Type1DecimalInputWidget</name>
    <message>
        <source>.</source>
        <translation>.</translation>
    </message>
</context>
<context>
    <name>Type1FractionInputWidget</name>
    <message>
        <source>/</source>
        <translation>/</translation>
    </message>
</context>
<context>
    <name>Type2InputWidget</name>
    <message>
        <source>9</source>
        <translation>9</translation>
    </message>
    <message>
        <source>6</source>
        <translation>6</translation>
    </message>
    <message>
        <source>3</source>
        <translation>3</translation>
    </message>
    <message>
        <source>7</source>
        <translation>7</translation>
    </message>
    <message>
        <source>4</source>
        <translation>4</translation>
    </message>
    <message>
        <source>=</source>
        <translation>=</translation>
    </message>
    <message>
        <source>8</source>
        <translation>8</translation>
    </message>
    <message>
        <source>2</source>
        <translation>2</translation>
    </message>
    <message>
        <source>1</source>
        <translation>1</translation>
    </message>
    <message>
        <source>5</source>
        <translation>5</translation>
    </message>
    <message>
        <source>/</source>
        <translation>/</translation>
    </message>
    <message>
        <source>x</source>
        <translation>x</translation>
    </message>
    <message>
        <source>-</source>
        <translation>-</translation>
    </message>
    <message>
        <source>+</source>
        <translation>+</translation>
    </message>
    <message>
        <source>0</source>
        <translation>0</translation>
    </message>
    <message>
        <source>.</source>
        <translation>.</translation>
    </message>
</context>
</TS>
