qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=host
dir=src/testlib
depends(libraries/qt/corelib)

idep(CONFIG += qtestlib)
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qt/corelib)
