qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=lib
qt=target
dir=src/testlib
depends(libraries/qtopiacore/corelib)

idep(CONFIG += qtestlib)
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qtopiacore/corelib)
