TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=words

MODULES*=inputmatch
CONFIG+=quicklaunch

include(words.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

