TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=qkeyboard

PLUGIN_FOR=qtopia
PLUGIN_TYPE=inputmethods

include(keyboard.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

