TEMPLATE=app
CONFIG+=qtopia
TARGET=fixbdaddr

QTOPIA*=phone
CONFIG+=quicklaunch

include(fixbdaddr.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

