<!DOCTYPE TS><TS>
<context>
    <name>Board</name>
    <message>
        <source>Blanks: </source>
        <translation>空き:</translation>
    </message>
    <message>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation>取り消し</translation>
    </message>
    <message>
        <source>Unknown word</source>
        <translation>不明な単語です</translation>
    </message>
    <message>
        <source>&lt;p&gt;The word &quot;%1&quot; is not in the dictionary.</source>
        <translation>&lt;p&gt;辞書にありません。</translation>
    </message>
    <message>
        <source>Add</source>
        <translation>追加</translation>
    </message>
    <message>
        <source>Ignore</source>
        <translation>無視</translation>
    </message>
</context>
<context>
    <name>NewGameBase</name>
    <message>
        <source>Players</source>
        <translation>プレーヤー</translation>
    </message>
    <message>
        <source>AI3: Smart AI player</source>
        <translation>A13：スマートA1プレーヤー</translation>
    </message>
    <message>
        <source>&amp;Start</source>
        <translation>(&amp;S)スタート</translation>
    </message>
    <message>
        <source>Rules:</source>
        <translation>ルール:</translation>
    </message>
    <message>
        <source>New Game</source>
        <translation>新規ゲーム</translation>
    </message>
</context>
<context>
    <name>RulesBase</name>
    <message>
        <source>Game Rules</source>
        <translation>ゲームのルール</translation>
    </message>
    <message>
        <source>Name:</source>
        <translation>名前:</translation>
    </message>
    <message>
        <source>Board</source>
        <translation>ボード</translation>
    </message>
    <message>
        <source>Size:</source>
        <translation>サイズ:</translation>
    </message>
    <message>
        <source>Edit...</source>
        <translation>編集...</translation>
    </message>
    <message>
        <source>Delete</source>
        <translation>削除</translation>
    </message>
    <message>
        <source>&amp;OK</source>
        <translation>(&amp;O)OK</translation>
    </message>
    <message>
        <source>&amp;Cancel</source>
        <translation>(&amp;C)取り消し</translation>
    </message>
</context>
<context>
    <name>ScoreInfo</name>
    <message>
        <source>&lt;P&gt;Invalid move</source>
        <translation>&lt;P&gt;無効な移動です</translation>
    </message>
    <message>
        <source>&lt;P&gt;Score: </source>
        <translation>&lt;P&gt;得点:</translation>
    </message>
</context>
<context>
    <name>WordGame</name>
    <message>
        <source>Word Game</source>
        <translation>ワードゲーム</translation>
    </message>
    <message>
        <source>Back</source>
        <translation>後へ</translation>
    </message>
    <message>
        <source>Done</source>
        <translation>完成</translation>
    </message>
    <message>
        <source>Close</source>
        <translation>閉じる</translation>
    </message>
    <message>
        <source>Player</source>
        <translation>プレーヤー</translation>
    </message>
    <message>
        <source>End game</source>
        <translation>ゲーム終了</translation>
    </message>
    <message>
        <source>Do you want to end the game early?</source>
        <translation>途中でゲームを終了しますか？</translation>
    </message>
    <message>
        <source>Yes</source>
        <translation>はい</translation>
    </message>
    <message>
        <source>No</source>
        <translation>いいえ</translation>
    </message>
</context>
</TS>
