TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=callforwarding

QTOPIA*=pim
CONFIG+=quicklaunch

include(callforwarding.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

