#!/bin/bash

. /opt/Qtopia/SDK/scripts/devel-x86.sh

qw_display=0

PHONESKINNAME=Greenphone.skin

echo "Using qvfb skin $PHONESKINNAME"

PHONESKIN=/opt/Qtopia/SDK/$QPEVER/greenphone/qtopiacore/qt/tools/qvfb/$PHONESKINNAME


start_qvfb()
{
    if [ ! -e /tmp/.qtvfb_keyboard-$1 ]; then
        echo "Starting qvfb... "
        echo "$QTDIR/bin/qvfb :$1 -skin $PHONESKIN"
        killall qvfb
        qvfb -zoom .75 -qwsdisplay :$1 -skin $PHONESKIN &
    fi
}

start_qvfb $qw_display

