#!/bin/bash

. /opt/Qtopia/SDK/scripts/functions

QPEVER=`version`

export QTOPIA_PHONE_DEVICE="sim:127.0.0.1"
#export QTOPIA_PHONE_DUMMY=1
source /opt/Qtopia/SDK/scripts/devel-x86.sh
# phonesim -gui $HOME/scripts/troll.xml &
# phonesim_target $HOMEx/scripts/troll.xml &
home-runqvfb &
runphonesim &
sleep 2
/opt/Qtopia/SDK/scripts/runqpe-x86 2>&1 |logger -t 'x86'
