#!/bin/sh

. /opt/Qtopia/SDK/scripts/functions

QPEVER=`version`

prepare_device()
{
    ssh root@$PHONEIP 'updateqtopiahelper killqtopia'
    ssh root@$PHONEIP 'updateqtopiahelper unmountqtopia'
    ssh root@$PHONEIP 'gifanim /mnt/user/tools/splash.gif'
}

extract_image()
{
    tar -C $TEMPDIR -xzf $QTOPIA_IMAGE
}

upload_image()
{
    IMAGE_SIZE=0
    for file in $TEMPDIR/*; do
        IMAGE_SIZE=$(($IMAGE_SIZE + `stat -c %s $file`))
    done
    IMAGE_SIZE=$(( (1 + $IMAGE_SIZE / 1048576) * 1048576 ))

    MNTPNT=$( ssh root@$PHONEIP "updateqtopiahelper createtemp $IMAGE_SIZE" )

    for i in $TEMPDIR/* ; do
        scp $i root@$PHONEIP:$MNTPNT
    done
}

install_image()
{
    ssh root@$PHONEIP "updateqtopia --ignore-firstrun --dont-reboot $MNTPNT"
    ssh root@$PHONEIP "updateqtopiahelper deletetemp $MNTPNT"
    ssh root@$PHONEIP "reboot"
}

if [ $# -eq 0 ]; then
    QTOPIA_IMAGE=/opt/Qtopia/extras/images/qtopia-greenphone-update.tar.gz
elif [ $# -eq 1 ]; then    
    case "$1" in
        /*)
            QTOPIA_IMAGE="$1"
            ;;
        *)
            QTOPIA_IMAGE="`pwd`/$1"
            ;;
    esac
else
    echo "usage: $0 [image]"
    exit 1
fi

TEMPDIR=`mktemp -d /tmp/updatedevice.XXXXXX`
trap 'rm -rf $TEMPDIR' 0

if gph -net; then
  echo "Network up, continue with flash"
else
  exit
fi
echo "Starting Flash process, please wait..."
prepare_device
echo "device prep stage complete."
extract_image
echo "extract stage complete."
upload_image
echo "uploading image stage complete."
echo
echo "Flashing begins..........please wait....."
install_image
echo "Image installed, phone will reset automatically and start Qtopia"
echo
echo

