#!/bin/sh

. /opt/Qtopia/SDK/scripts/functions

QPEVER=`version`

prepare_device()
{
    cd $TEMPDIR
    
    HELPER=updatedevice_helper.sh
    cat >$HELPER <<EOF
#!/bin/sh
export PATH=/mnt/user/tools:/opt/Qtopia/bin:/usr/bin:/bin:/sbin:/usr/sbin
killall qpe.sh qpe quicklauncher sipagent qss netsetup
LIST=\`ps |sed -n -e '/Qtopia/ s/root.*//p'\`
for i in \$LIST; do 
    kill $i 2>/dev/null
done
sleep 5
umount /opt/Qtopia.rom 2>/dev/null
echo "">/etc/resolv.conf
/usr/local/bin/gifanim /mnt/user/tools/splash.gif &
sleep 5
sync
EOF

    ftpput -u anonymous $PHONEIP / $HELPER
    rm -f $HELPER

    expect -c '
        set timeout 300;
        log_user 0;
        
        spawn telnet '$PHONEIP';
        expect {
            default {
                send_user "Could not connect to Greenphone."
                exit 1
            } root@
        }

        send "chmod 555 /mnt/user_local/updatedevice_helper.sh\r";
        expect root@;
        
        send "/mnt/user_local/updatedevice_helper.sh\r";
        expect root@
    '
}

extract_image()
{
    tar -C $TEMPDIR -xzf $QTOPIA_IMAGE
}

upload_image_tmpfs()
{
    expect -c '
        set timeout 300;
        log_user 0;
        
        spawn telnet '$PHONEIP';
        expect {
            default {
                send_error "Could not connect to Greenphone."
                exit 1
            } root@
        }

        send "MNTPNT=`mktemp -d /mnt/user_local/updatedevice.XXXXXX`\r";
        expect root@

        send "mount -t tmpfs -o size='$IMAGE_SIZE' tmpfs \$MNTPNT\r";
        expect root@
        
        send "echo \$MNTPNT\r";
        expect -re "updatedevice\......." {
            send_user "$expect_out(0,string)";
        }
    ' 
}

upload_image()
{
    IMAGE_SIZE=0
    for file in $TEMPDIR/*; do
        IMAGE_SIZE=$(($IMAGE_SIZE + `stat -c %s $file`))
    done
    IMAGE_SIZE=$(( (1 + $IMAGE_SIZE / 1048576) * 1048576 ))

    MNTPNT=`upload_image_tmpfs`

    cd $TEMPDIR
    for i in * ; do
        ftpput -u anonymous $PHONEIP /$MNTPNT $i
    done

    HELPER=updatedevice_helper.sh
    cat >$HELPER <<EOF
#!/bin/sh
umount /mnt/sd
mount -o bind /mnt/user_local/$MNTPNT /mnt/sd
chmod 555 /mnt/sd/trolltech_flash.sh
/mnt/sd/trolltech_flash.sh --dont-reboot
sleep 5
sync
umount /mnt/sd
umount /mnt/user_local/$MNTPNT
rmdir /mnt/user_local/$MNTPNT
echo "FLASHFINISHED!"
EOF

    ftpput -u anonymous $PHONEIP / $HELPER
    rm -f $HELPER
}

install_image()
{
    expect -c '
        set timeout 800;
        log_user 0;
        
        spawn telnet '$PHONEIP';
        expect root@;
        
        send "chmod 555 /mnt/user_local/updatedevice_helper.sh\r";
        expect root@;
        
        send "/mnt/user_local/updatedevice_helper.sh\r";
        expect FLASHFINISHED

        send "rm -f /mnt/user_local/updatedevice_helper.sh ; sync\r";
        expect root@;

        send "reboot\r";
        expect root@;
    '
}

if [ $# -eq 0 ]; then
    QTOPIA_IMAGE=/opt/Qtopia/extras/images/qtopia-greenphone-update.tar.gz
elif [ $# -eq 1 ]; then    
    case "$1" in
        /*)
            QTOPIA_IMAGE="$1"
            ;;
        *)
            QTOPIA_IMAGE="`pwd`/$1"
            ;;
    esac
else
    echo "usage: $0 [image]"
    exit 1
fi

TEMPDIR=`mktemp -d /tmp/updatedevice.XXXXXX`

trap 'rm -rf $TEMPDIR' 0

if gph -net; then
  echo "Network up, continue with flash"
else
  exit
fi
echo "Starting Flash process, please wait..."
prepare_device
echo "device prep stage complete."
extract_image
echo "extract stage complete."
upload_image
echo "uploading image stage complete."
echo
echo "Flashing begins..........please wait....."
install_image
echo "Image installed, phone will reset automatically and start Qtopia"
echo
echo

