/****************************************************************************
**
** Copyright (C) 2000-2008 TROLLTECH ASA. All rights reserved.
**
** This file is part of the Opensource Edition of the Qtopia Toolkit.
**
** This software is licensed under the terms of the GNU General Public
** License (GPL) version 2.
**
** See http://www.trolltech.com/gpl/ for GPL licensing information.
**
** Contact info@trolltech.com if any conditions of this licensing are
** not clear to you.
**
**
**
** This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
** WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
**
****************************************************************************/
#ifndef QOUTLOOK_H
#define QOUTLOOK_H

#pragma warning(disable:4146)

// This file is generated by the findoutlook utility
#include "qoutlook_detect.h"

#pragma warning(default:4146)

using namespace Outlook;

// =====================================================================

#include <QDateTime>

QDateTime date_to_qdatetime( double date );
double qdatetime_to_date( const QDateTime &dt );
QString bstr_to_qstring( const _bstr_t &string );
_bstr_t qstring_to_bstr( const QString &string );
QString variant_to_qstring( const _variant_t &string );
_variant_t qstring_to_variant( const QString &string );

#endif
