TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=homescreen

CONFIG+=quicklaunch

include(homescreen.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

