qtopia_project(qtopiacore)
QTOPIACORE_CONFIG=ignore_errors lib
qt=host
dir=tools/designer/src/$$TARGET/lib
# generated by extract_qt_dependencies
# do not modify below this line!
depends(libraries/qt/script)
depends(libraries/qt/xml)
depends(libraries/qt/gui)
depends(libraries/qt/corelib)
depends(tools/qt/designer/src/lib)
