TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=worldtime

CONFIG+=quicklaunch

include(worldtime.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

