TEMPLATE	=  lib
CONFIG		+= qtopia warn_on release
HEADERS		=  wavplugin.h wavpluginimpl.h
SOURCES	        =  wavplugin.cpp wavpluginimpl.cpp
TARGET		=  wavplugin
DESTDIR		=  $(QPEDIR)/plugins/codecs
INCLUDEPATH	+= $(QPEDIR)/include
DEPENDPATH      += $(QPEDIR)/include
LIBS            += -lqpe
VERSION		=  1.0.0
