TEMPLATE=plugin
CONFIG+=qtopia singleexec
TARGET=bscidrmagent

PLUGIN_FOR=qtopia
PLUGIN_TYPE=drmagent

MODULES*=drmagent

include(bscidrmagent.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

