TEMPLATE=app
CONFIG+=qtopia
TARGET=bluetooth

QTOPIA*=comm
CONFIG+=quicklaunch singleexec

include(bluetooth.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

