<!DOCTYPE TS><TS>
<context>
    <name>Clock</name>
    <message>
        <source>Start</source>
        <translation>スタート</translation>
    </message>
    <message>
        <source>Stop</source>
        <translation>ストップ</translation>
    </message>
    <message>
        <source>&lt;b&gt;Daily Alarm:&lt;/b&gt;&lt;p&gt;</source>
        <translation>&lt;b&gt;デイリーアラーム:&lt;/b&gt;&lt;p&gt;</translation>
    </message>
    <message>
        <source>Clock</source>
        <translation>時計</translation>
    </message>
    <message>
        <source>OK</source>
        <translation>OK</translation>
    </message>
    <message>
        <source>Reset</source>
        <translation>リセット</translation>
    </message>
    <message>
        <source>Lap/Split</source>
        <translation>ラップ/スプリット</translation>
    </message>
    <message>
        <source>Mon</source>
        <comment>Monday</comment>
        <translation>月曜</translation>
    </message>
    <message>
        <source>Tue</source>
        <comment>Tuesday</comment>
        <translation>火曜</translation>
    </message>
    <message>
        <source>Wed</source>
        <comment>Wednesday</comment>
        <translation>水曜</translation>
    </message>
    <message>
        <source>Thu</source>
        <comment>Thursday</comment>
        <translation>木曜</translation>
    </message>
    <message>
        <source>Fri</source>
        <comment>Friday</comment>
        <translation>金曜</translation>
    </message>
    <message>
        <source>Sat</source>
        <comment>Saturday</comment>
        <translation>土曜</translation>
    </message>
    <message>
        <source>Sun</source>
        <comment>Sunday</comment>
        <translation>日曜</translation>
    </message>
</context>
<context>
    <name>ClockBase</name>
    <message>
        <source>Clock</source>
        <translation>時計</translation>
    </message>
    <message>
        <source>Stopwatch</source>
        <translation>ストップウォッチ</translation>
    </message>
    <message>
        <source>Start</source>
        <translation>スタート</translation>
    </message>
    <message>
        <source>Starts and stops the stopwatch.</source>
        <translation>ストップウォッチをスタート、ストップします。</translation>
    </message>
    <message>
        <source>Resets the stopwatch.</source>
        <translation>ストップウォッチをリセットします。</translation>
    </message>
    <message>
        <source>Alarms</source>
        <translation>アラーム</translation>
    </message>
    <message>
        <source>Daily Alarm</source>
        <translation>デイリーアラーム</translation>
    </message>
    <message>
        <source>Enabled</source>
        <translation>オン</translation>
    </message>
    <message>
        <source>Check to enable the daily alarm</source>
        <translation>チェックしてアラームをオンにします</translation>
    </message>
    <message>
        <source>Set the hour the alarm will sound.</source>
        <translation>アラームが鳴る時間を設定します。</translation>
    </message>
    <message>
        <source>:</source>
        <translation>:</translation>
    </message>
    <message>
        <source>Set the minute the alarm will sound.</source>
        <translation>アラームが鳴る分を設定します。</translation>
    </message>
    <message>
        <source>AM</source>
        <translation>AM</translation>
    </message>
    <message>
        <source>PM</source>
        <translation>PM</translation>
    </message>
    <message>
        <source>Countdown Alarm</source>
        <translation>カウントダウンアラーム</translation>
    </message>
    <message>
        <source>Split</source>
        <translation>スプリット</translation>
    </message>
    <message>
        <source>Lap</source>
        <translation>ラップ</translation>
    </message>
    <message>
        <source>Lap/Split</source>
        <translation>ラップ/スプリット</translation>
    </message>
    <message>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <source>Days:</source>
        <translation>曜日:</translation>
    </message>
</context>
</TS>
