TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=serverwidgets

CONFIG+=quicklaunch

include(serverwidgets.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

