TEMPLATE=app
CONFIG+=qtopia singleexec
TARGET=mindbreaker

CONFIG+=quicklaunch

include(mindbreaker.pro)

STRING_LANGUAGE=en_US
AVAILABLE_LANGUAGES=$$QTOPIA_AVAILABLE_LANGUAGES
LANGUAGES=$$QTOPIA_LANGUAGES

